### ISSUE TITLE
Upgrade to Django 4.1

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/actions-registry#132]
Django 4.1 [has been released](https://www.djangoproject.com/weblog/2022/aug/03/django-41-released/), and given it's our biggest dependency a bit more care needs to be taken with this upgrade.

We should check:
* [ ] `devserver` runs without errors, and look into/fix any deprecation warnings we can
* [ ] the tests run without errors or warnings, fixing what we can
* [ ] Read through [the release notes](https://docs.djangoproject.com/en/4.1/releases/4.1/) to look for anything this project uses in case there's something the previous two points don't capture.

**Comment by iaindillingham** [comment]
#216
