### ISSUE TITLE
Potentially replace actions registry website with GitHub org

### ISSUE THREAD

**Issue by tomodwyer** [opensafely-core/actions-registry#171]
https://github.com/opensafely-actions contains a duplicate of the information hosted on this website. We should archive this website and direct users to GitHub instead.

- [ ] Remove from uptime checks
- [ ] Create redirects on Cloudflare (see below)
- [ ] Close issues and PRs on repo
- [ ] Archive existing repository
- [ ] Remove app from server

```
https://actions.opensafely.org/             => https://github.com/opensafely-actions
https://actions.opensafely.org/actions/*    => https://github.com/opensafely-actions/$1
https://actions.opensafely.org/actions/*/*/ => https://github.com/opensafely-actions/$1/releases/tag/$2
```

**Comment by iaindillingham** [comment]
I'm going to close this issue as when we discussed it, we agreed that it was good to have a stand-alone actions registry website.
